import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import top_search from "../img/top-search.png";
import arrow_left from "../img/arrow-left.png";
import arrow_right from "../img/arrow-right.png";
import brand_logo from "../img/brand-logo.png";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopSection></TopSection>
      <JustAbovFooter></JustAbovFooter>
      <FooterSection></FooterSection>
    </>
  );
}

function TopSection() {
  return (
    <div className="top-main-container">
      <div>
        <span>
          <Image src={top_search} alt="image" />
        </span>
        <span>
          Test out the first ever visual search tool for the art industry -&gt;
        </span>
      </div>

      <div className="blur-1"></div>

      <div className="waitlist-div">
        <div>
          <span className="brand_logo">
            <Image src={brand_logo} alt="logo" />
          </span>

          <button>
            <Image src={arrow_left} alt="arrow" />
            Join Waitlist
          </button>
        </div>
      </div>

      <div className="blur-2">
        <div>
          <h1>Co-Pilot for the Art Industry</h1>
          <p>
            Augier Art is building a tool set for galleries and art institutions
            to automate tedious workflows and unlock business insights using
            data
          </p>
        </div>
      </div>

      <div className="video">
        <video src=""></video>

        <button>
          Learn More
          <Image src={arrow_right} alt="arrow" />
        </button>
      </div>
    </div>
  );
}

function FooterSection() {
  return (
    <div className="footer-section">
      <div>
        <Image src={brand_logo} alt="logo" />
        <p>AI enabling the art market</p>
        <p>&copy; 2023 Augier Art Inc. All rights reserved.</p>
      </div>

      <div>
        <ul>
          <li>About</li>
          <li>FAQs</li>
          <li>Our Tools</li>
        </ul>

        <ul>
          <li>Search</li>
          <li>Gallery Upload</li>
          <li>Join Waitlist</li>
        </ul>
      </div>
    </div>
  );
}

function JustAbovFooter() {
  return (
    <div className="justAbovFooter">
      <div className="content">
        <div></div>
        <div></div>
      </div>

      <div className="under-content">
        <div>
          <div>
            <span>Join our Community of Galleries</span>
            <input type="text" placeholder="Enter your email..." />
          </div>

          <div>
            <span>Recommend a feature or tool</span>
            <input type="text" placeholder="What would like to see next?..." />
          </div>
        </div>
      </div>
    </div>
  );
}
